# Generated by Django 5.1.5 on 2025-01-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('duration', models.FloatField(help_text='Duration in seconds')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shared_link', models.URLField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
